mod_name=No Boat Cheesing
mod_id=no_boat_cheesing
mod_description=Mobs will now leave their boats/minecarts if attacking/fleeing/tempted.
mod_version=1.0
mc_version=1.21.1

kotlin_version=2.3.10
fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.18.4
fabric_kotlin_version_prefix=1.13.9

mc_to_java_version=26.1: 25, 1.20.5: 21, 1.18: 17, 1.17: 16, 1.0: 8

org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
